In [2]:
import cv2
import numpy as np
import os
import glob

In [3]:
CHECKERBOARD = (7,7)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

In [4]:
# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 

In [5]:
objp = np.zeros((1, CHECKERBOARD[0] * CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None

In [6]:
# Extracting path of individual image stored in a given directory
images = glob.glob('./images/*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_NORMALIZE_IMAGE)
     
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray, corners, (11,11),(-1,-1), criteria)
         
        imgpoints.append(corners2)
 
        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2, ret)
     
    cv2.imshow('img',img)
    cv2.waitKey(0)
 
cv2.destroyAllWindows()
 
h,w = img.shape[:2]

In [7]:
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
 
print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

Camera matrix : 

[[1.40894054e+03 0.00000000e+00 6.21548603e+02]
 [0.00000000e+00 1.41419267e+03 4.36870727e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
dist : 

[[ 1.20133890e-01  2.87074381e-01  1.22318077e-02 -4.77015667e-04
  -2.82576151e+00]]
rvecs : 

(array([[-0.06039192],
       [-0.07066559],
       [ 0.01061699]]), array([[-0.1061295 ],
       [-0.03726059],
       [ 0.04038762]]), array([[0.05146351],
       [0.6560305 ],
       [3.06407698]]), array([[0.04255977],
       [0.62899135],
       [1.63899515]]), array([[0.03800245],
       [0.63487089],
       [1.64829846]]), array([[-0.31370899],
       [ 0.69560937],
       [ 1.51571496]]), array([[0.07976391],
       [0.09634009],
       [1.50309993]]), array([[-0.04855251],
       [-0.20441997],
       [ 0.0250042 ]]), array([[ 0.09950646],
       [-0.5434962 ],
       [-0.01135899]]), array([[ 0.04702284],
       [-0.50622954],
       [-0.00132085]]), array([[0.07395182],
       [0.57212289],
       [1.51789415]])